/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubvencijeRouteImport } from './routes/subvencije'
import { Route as ONamaRouteImport } from './routes/o-nama'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KalkulatorRouteImport } from './routes/kalkulator'
import { Route as KakoFunkcioniraRouteImport } from './routes/kako-funkcionira'
import { Route as InstalateriRouteImport } from './routes/instalateri'
import { Route as FinanciranjeRouteImport } from './routes/financiranje'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'

const SubvencijeRoute = SubvencijeRouteImport.update({
  id: '/subvencije',
  path: '/subvencije',
  getParentRoute: () => rootRouteImport,
} as any)
const ONamaRoute = ONamaRouteImport.update({
  id: '/o-nama',
  path: '/o-nama',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KalkulatorRoute = KalkulatorRouteImport.update({
  id: '/kalkulator',
  path: '/kalkulator',
  getParentRoute: () => rootRouteImport,
} as any)
const KakoFunkcioniraRoute = KakoFunkcioniraRouteImport.update({
  id: '/kako-funkcionira',
  path: '/kako-funkcionira',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalateriRoute = InstalateriRouteImport.update({
  id: '/instalateri',
  path: '/instalateri',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanciranjeRoute = FinanciranjeRouteImport.update({
  id: '/financiranje',
  path: '/financiranje',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/faq': typeof FaqRoute
  '/financiranje': typeof FinanciranjeRoute
  '/instalateri': typeof InstalateriRoute
  '/kako-funkcionira': typeof KakoFunkcioniraRoute
  '/kalkulator': typeof KalkulatorRoute
  '/kontakt': typeof KontaktRoute
  '/o-nama': typeof ONamaRoute
  '/subvencije': typeof SubvencijeRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/financiranje': typeof FinanciranjeRoute
  '/instalateri': typeof InstalateriRoute
  '/kako-funkcionira': typeof KakoFunkcioniraRoute
  '/kalkulator': typeof KalkulatorRoute
  '/kontakt': typeof KontaktRoute
  '/o-nama': typeof ONamaRoute
  '/subvencije': typeof SubvencijeRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/faq': typeof FaqRoute
  '/financiranje': typeof FinanciranjeRoute
  '/instalateri': typeof InstalateriRoute
  '/kako-funkcionira': typeof KakoFunkcioniraRoute
  '/kalkulator': typeof KalkulatorRoute
  '/kontakt': typeof KontaktRoute
  '/o-nama': typeof ONamaRoute
  '/subvencije': typeof SubvencijeRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/faq'
    | '/financiranje'
    | '/instalateri'
    | '/kako-funkcionira'
    | '/kalkulator'
    | '/kontakt'
    | '/o-nama'
    | '/subvencije'
    | '/admin/dashboard'
    | '/admin/login'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/financiranje'
    | '/instalateri'
    | '/kako-funkcionira'
    | '/kalkulator'
    | '/kontakt'
    | '/o-nama'
    | '/subvencije'
    | '/admin/dashboard'
    | '/admin/login'
    | '/blog/$slug'
    | '/admin'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/faq'
    | '/financiranje'
    | '/instalateri'
    | '/kako-funkcionira'
    | '/kalkulator'
    | '/kontakt'
    | '/o-nama'
    | '/subvencije'
    | '/admin/dashboard'
    | '/admin/login'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  FaqRoute: typeof FaqRoute
  FinanciranjeRoute: typeof FinanciranjeRoute
  InstalateriRoute: typeof InstalateriRoute
  KakoFunkcioniraRoute: typeof KakoFunkcioniraRoute
  KalkulatorRoute: typeof KalkulatorRoute
  KontaktRoute: typeof KontaktRoute
  ONamaRoute: typeof ONamaRoute
  SubvencijeRoute: typeof SubvencijeRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subvencije': {
      id: '/subvencije'
      path: '/subvencije'
      fullPath: '/subvencije'
      preLoaderRoute: typeof SubvencijeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nama': {
      id: '/o-nama'
      path: '/o-nama'
      fullPath: '/o-nama'
      preLoaderRoute: typeof ONamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalkulator': {
      id: '/kalkulator'
      path: '/kalkulator'
      fullPath: '/kalkulator'
      preLoaderRoute: typeof KalkulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kako-funkcionira': {
      id: '/kako-funkcionira'
      path: '/kako-funkcionira'
      fullPath: '/kako-funkcionira'
      preLoaderRoute: typeof KakoFunkcioniraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalateri': {
      id: '/instalateri'
      path: '/instalateri'
      fullPath: '/instalateri'
      preLoaderRoute: typeof InstalateriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financiranje': {
      id: '/financiranje'
      path: '/financiranje'
      fullPath: '/financiranje'
      preLoaderRoute: typeof FinanciranjeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  FaqRoute: FaqRoute,
  FinanciranjeRoute: FinanciranjeRoute,
  InstalateriRoute: InstalateriRoute,
  KakoFunkcioniraRoute: KakoFunkcioniraRoute,
  KalkulatorRoute: KalkulatorRoute,
  KontaktRoute: KontaktRoute,
  ONamaRoute: ONamaRoute,
  SubvencijeRoute: SubvencijeRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
